/**
 * Generates web/migrations/0002_seed.sql from the repo's own artifacts:
 * styles/*.yaml become house styles, brand/brand.json becomes the house brand kit.
 * Run from the repo root:  node web/scripts/gen-seed.mjs
 *
 * Regenerating rewrites the file; migrations only ever apply once, so a re-run after
 * the migration has been applied is a no-op on the database.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { listStyles } from '../../src/style-fs.ts';

const q = (s) => (s === null || s === undefined ? 'NULL' : `'${String(s).replaceAll("'", "''")}'`);
const now = new Date().toISOString();

// Stable, readable ids for seed rows; generated rows use ULIDs.
const U_MATE = 'seed_user_mate';
const T_HOUSE = 'seed_team_house';
const T_MWK = 'seed_team_mwk';
const BK_HOUSE = 'seed_brandkit_mwk';

const lines = [
  '-- 0002_seed — generated by web/scripts/gen-seed.mjs. Do not edit by hand.',
  '',
  `INSERT INTO user (id, email, name, created_at) VALUES (${q(U_MATE)}, 'suzanne@tasmanvisa.com', 'Mate', ${q(now)});`,
  '',
  `INSERT INTO team (id, name, slug, kind, created_by, created_at) VALUES (${q(T_HOUSE)}, 'House', 'house', 'house', ${q(U_MATE)}, ${q(now)});`,
  `INSERT INTO team (id, name, slug, kind, created_by, created_at) VALUES (${q(T_MWK)}, 'Mate Wish Key', 'mwk', 'normal', ${q(U_MATE)}, ${q(now)});`,
  `INSERT INTO team_member (team_id, user_id, role, joined_at) VALUES (${q(T_MWK)}, ${q(U_MATE)}, 'owner', ${q(now)});`,
  '',
];

const brand = await readFile('brand/brand.json', 'utf8');
lines.push(
  `INSERT INTO brand_kit (id, team_id, slug, name, config, default_title, default_tagline, created_at, updated_at)` +
    ` VALUES (${q(BK_HOUSE)}, ${q(T_HOUSE)}, 'mwk', 'Mate Wish Key', ${q(brand)},` +
    ` 'Mate *Wish* Key', 'No code. Just prompts. Wishes delivered.', ${q(now)}, ${q(now)});`,
  '',
);

for (const s of await listStyles()) {
  lines.push(
    `INSERT INTO style (id, team_id, slug, name, description, look, subject, avoid, tags, origin, created_at, updated_at)` +
      ` VALUES (${q('seed_style_' + s.slug.replaceAll('-', '_'))}, ${q(T_HOUSE)}, ${q(s.slug)}, ${q(s.name)}, ${q(s.description)},` +
      ` ${q(s.look)}, ${q(s.subject)}, ${q(s.avoid)}, ${q(JSON.stringify(s.tags))}, ${q(s.origin)}, ${q(now)}, ${q(now)});`,
  );
}

await writeFile('web/migrations/0002_seed.sql', lines.join('\n') + '\n');
console.log(`0002_seed.sql written: ${(await listStyles()).length} styles, 1 brand kit, 2 teams, 1 user`);
