-- 0002_seed — generated by web/scripts/gen-seed.mjs. Do not edit by hand.

INSERT INTO user (id, email, name, created_at) VALUES ('seed_user_mate', 'suzanne@tasmanvisa.com', 'Mate', '2026-08-14T13:49:07.085Z');

INSERT INTO team (id, name, slug, kind, created_by, created_at) VALUES ('seed_team_house', 'House', 'house', 'house', 'seed_user_mate', '2026-08-14T13:49:07.085Z');
INSERT INTO team (id, name, slug, kind, created_by, created_at) VALUES ('seed_team_mwk', 'Mate Wish Key', 'mwk', 'normal', 'seed_user_mate', '2026-08-14T13:49:07.085Z');
INSERT INTO team_member (team_id, user_id, role, joined_at) VALUES ('seed_team_mwk', 'seed_user_mate', 'owner', '2026-08-14T13:49:07.085Z');

INSERT INTO brand_kit (id, team_id, slug, name, config, default_title, default_tagline, created_at, updated_at) VALUES ('seed_brandkit_mwk', 'seed_team_house', 'mwk', 'Mate Wish Key', '{
  "$comment": "Mate Wish Key OG card, built from the published design system at matewishkey.com/design. Dark-theme tokens throughout, because the band is always a dark ground.",
  "canvas": {
    "width": 1200,
    "height": 630
  },
  "colors": {
    "paper": "#101317",
    "ink": "#f4f2f6",
    "mute": "#a8a2b0",
    "faint": "#8e8896",
    "red": "#e2342b",
    "redField": "#c9251d",
    "redDeep": "#f0524a",
    "line": "#232c3a",
    "onRed": "#ffffff"
  },
  "scrim": {
    "startY": 300,
    "opacity": 0.96
  },
  "band": {
    "height": 150,
    "opacity": 0.94,
    "ruleHeight": 3
  },
  "logo": {
    "$comment": "The RedBlock is the only logo: a red square, square corners, white mark centred at 64%. Never a bare mark.",
    "mark": "brand/mwk-mark-white.svg",
    "size": 76,
    "markScale": 0.64,
    "x": 56
  },
  "title": {
    "$comment": "Display heading / wordmark. Fraunces 700 per the design system. Wrap a word in *asterisks* to set it in red \u2014 that is how the ''Mate *Wish* Key'' wordmark is written.",
    "family": "Fraunces",
    "file": "brand/fonts/Fraunces[SOFT,WONK,opsz,wght].ttf",
    "size": 38,
    "weight": 700,
    "gap": 28
  },
  "kicker": {
    "$comment": "LABEL/KICKER: JetBrains Mono 700, uppercase, 0.16em tracking, red-deep \u2014 the only red allowed at body size.",
    "family": "JetBrains Mono",
    "file": "brand/fonts/JetBrainsMono[wght].ttf",
    "size": 15,
    "weight": 700,
    "trackingEm": 0.16,
    "gapBelow": 12
  },
  "tagline": {
    "$comment": "Standfirst under the wordmark. Manrope at body weight in --mute, per the design system''s rule that Manrope is body copy and mute carries standfirsts.",
    "family": "Manrope",
    "file": "brand/fonts/Manrope[wght].ttf",
    "size": 19,
    "weight": 500,
    "gapAbove": 9
  }
}', 'Mate *Wish* Key', 'No code. Just prompts. Wishes delivered.', '2026-08-14T13:49:07.085Z', '2026-08-14T13:49:07.085Z');

INSERT INTO style (id, team_id, slug, name, description, look, subject, avoid, tags, origin, created_at, updated_at) VALUES ('seed_style_bricks_for_real', 'seed_team_house', 'bricks-for-real', 'Bricks For Real', 'Photoreal editorial photography where brick-built objects sit in the real world at real scale. One look for a four-panel series whose stakes escalate: the toy stays a toy, but the world around it gets more serious.', 'Documentary editorial photography, shot on a 35mm lens at f/4 with available light plus one soft fill. Natural colour, realistic contrast, real depth of field, honest skin tones and believable environmental grain — a photograph a magazine would run, not a render. The brick-built object in frame is genuinely made of moulded plastic construction bricks, with visible studs, moulding seams, panel gaps and slight misalignment, but it occupies real space in a real place at whatever scale the scene demands. Composition leaves the bottom of the frame calm.', 'People are ordinary adults photographed straight — real clothes, real posture, unposed expressions. Never minifigures, never stylised, never caricatured.', '3D render, CGI gloss, cartoon, illustration, studio toy-photography sweep, cute mascots, smiling stock-photo faces', '["photographic","documentary","editorial","escalating"]', 'hand', '2026-08-14T13:49:07.085Z', '2026-08-14T13:49:07.085Z');
INSERT INTO style (id, team_id, slug, name, description, look, subject, avoid, tags, origin, created_at, updated_at) VALUES ('seed_style_cinematic_portrait', 'seed_team_house', 'cinematic-portrait', 'Cinematic Portrait', 'Moody photographic close-up. The default when a real face has to carry the card.', 'Photographic, shot on a full-frame camera with an 85mm lens at f/1.8, shallow depth of field. Single hard key light from one side with deep falloff into near-black shadow, a cold rim light on the opposite edge. Desaturated palette with one warm accent — amber or ember red — against charcoal and dark teal. Fine film grain, subtle halation on the highlights. Composed off-centre with generous negative space.', 'Rendered as a real photograph of them, not a stylisation. Keep the face sharp and well-lit, expression readable, no cosmetic smoothing.', 'flat even lighting, stock-photo smiling, cluttered background, HDR look, plastic skin', '["photographic","dramatic","portrait"]', 'hand', '2026-08-14T13:49:07.085Z', '2026-08-14T13:49:07.085Z');
INSERT INTO style (id, team_id, slug, name, description, look, subject, avoid, tags, origin, created_at, updated_at) VALUES ('seed_style_clay_desk_theater', 'seed_team_house', 'clay-desk-theater', 'Clay Desk Theater', 'For wry workplace commentary turned into a tactile miniature visual metaphor.', 'Handmade stop-motion clay and foam-board miniature construction, lit with a warm tabletop key light and soft, oversized shadows. Use dusty primary accents against oatmeal, charcoal, and muted teal surfaces, with visible fingerprints, seams, and slightly wonky handcrafted geometry. Compose in an elevated three-quarter view like a tiny diorama photographed on a macro lens.', 'Render the person as a small sculpted clay figure with recognizable adult proportions, simple features, and expressive body language. Keep them plausibly human rather than toy-cute, using a restrained eyebrow, hunched shoulder, or hovering hand to suggest discomfort.', 'plastic toy sheen, Pixar polish, photoreal faces, candy colors', '["clay","miniature","tactile"]', 'openai/gpt-5.6-terra', '2026-08-14T13:49:07.085Z', '2026-08-14T13:49:07.085Z');
INSERT INTO style (id, team_id, slug, name, description, look, subject, avoid, tags, origin, created_at, updated_at) VALUES ('seed_style_compliance_snapshot', 'seed_team_house', 'compliance-snapshot', 'Compliance Snapshot', 'For dry professional observations presented with the quiet absurdity of an internal workplace photo.', 'Naturalistic documentary photography with slightly imperfect overhead office lighting, cool gray walls, muted navy, beige, and printer-white tones. Frame it like a candid corporate training still on a 35mm lens: mildly wide, observational, with believable clutter and soft digital-camera grain. The mood is restrained, procedural, and subtly comic.', 'Render the person as an unglamorous real professional caught mid-task, with credible posture, wardrobe, and small facial reactions. Avoid polished headshot posing; their expression should carry the joke through a tiny look of concern, suspicion, or resignation.', 'cinematic grading, glamour lighting, exaggerated comedy, futuristic interfaces', '["photo","office","deadpan"]', 'openai/gpt-5.6-terra', '2026-08-14T13:49:07.085Z', '2026-08-14T13:49:07.085Z');
INSERT INTO style (id, team_id, slug, name, description, look, subject, avoid, tags, origin, created_at, updated_at) VALUES ('seed_style_flat_editorial', 'seed_team_house', 'flat-editorial', 'Flat Editorial', 'Vector editorial illustration. Best for a concept or a joke rather than a person.', 'Flat vector editorial illustration in the style of a broadsheet tech column. Bold simple shapes, no gradients beyond a single subtle paper grain, thick confident outlines used sparingly. Limited palette of four colours: off-white, deep ink navy, a muted clay red, one bright accent. Generous white space, strong diagonal composition, slightly oversized props to carry the metaphor.', 'Reduced to a simple flat character with the same hair, build and glasses as the reference, recognisable by silhouette rather than by facial detail.', 'gradients, drop shadows, 3D shading, photorealism, corporate clip-art', '["vector","editorial","conceptual"]', 'hand', '2026-08-14T13:49:07.085Z', '2026-08-14T13:49:07.085Z');
INSERT INTO style (id, team_id, slug, name, description, look, subject, avoid, tags, origin, created_at, updated_at) VALUES ('seed_style_marked_up_memo', 'seed_team_house', 'marked-up-memo', 'Marked-Up Memo', 'For sharp, knowing advice that should feel like a confidential note passed around a smart office.', 'A graphic collage built from scanned paper, typed memorandum fragments, photocopied forms, underlines, circles, and sparse pen annotations. Palette is off-white, faded black, bureaucratic blue, and one assertive red correction mark, with toner noise, folded-paper shadows, and imperfect registration. The composition should feel like a desk document enlarged into a bold editorial cover.', 'Render the person as a grainy halftone cutout or ID-photo-style portrait integrated into the paper layout. Keep the face legible but slightly anonymized by cropping, marker strokes, or overlapping labels, as though it belongs in an internal case file.', 'clean vector icons, neon colors, glossy photography, dense paperwork', '["collage","memo","editorial"]', 'openai/gpt-5.6-terra', '2026-08-14T13:49:07.085Z', '2026-08-14T13:49:07.085Z');
INSERT INTO style (id, team_id, slug, name, description, look, subject, avoid, tags, origin, created_at, updated_at) VALUES ('seed_style_neon_terminal', 'seed_team_house', 'neon-terminal', 'Neon Terminal', 'Late-night developer energy. Screens, glow, dark room.', 'Cinematic dark interior lit almost entirely by screens. Deep near-black background with cyan and magenta screen glow spilling across surfaces, volumetric haze catching the light, wet reflective desk. Long exposure feel with slight motion smear on the edges. Shallow focus, heavy bokeh from distant LEDs. Colour graded cold with a single hot red practical light somewhere in frame.', 'Lit from below and in front by the monitor, face half in shadow, expression concentrated. Keep them clearly recognisable.', 'daylight, clean bright offices, floating UI holograms, matrix green code rain', '["dark","cinematic","tech"]', 'hand', '2026-08-14T13:49:07.085Z', '2026-08-14T13:49:07.085Z');
INSERT INTO style (id, team_id, slug, name, description, look, subject, avoid, tags, origin, created_at, updated_at) VALUES ('seed_style_riso_print', 'seed_team_house', 'riso-print', 'Riso Print', 'Two-colour risograph poster. Loud, cheap-looking on purpose, scroll-stopping.', 'Two-colour risograph print on rough uncoated stock. Exactly two inks — fluorescent red and deep blue — overprinting into a third colour where they cross. Visible halftone dot texture, deliberate 1-2mm misregistration, ink smudging at the edges, paper fibre showing through. Bold poster composition, subject large in frame, heavy crop.', 'Reduced to high-contrast halftone with blown-out highlights and solid shadow shapes, still clearly the same person by hair, glasses and jawline.', 'more than two inks, smooth gradients, digital cleanliness, perfect registration', '["print","graphic","bold"]', 'hand', '2026-08-14T13:49:07.085Z', '2026-08-14T13:49:07.085Z');
INSERT INTO style (id, team_id, slug, name, description, look, subject, avoid, tags, origin, created_at, updated_at) VALUES ('seed_style_toy_macro', 'seed_team_house', 'toy-macro', 'Toy Macro', 'Studio macro photography of plastic toys. One consistent look so a set of scenes reads as a series rather than four unrelated pictures.', 'Macro product photography of real plastic construction bricks on a seamless studio sweep. Shot on a 100mm macro lens at f/8 so the whole miniature is sharp, with a big soft key from the upper left, a cool fill from the right, and crisp contact shadows. Slight tilt-shift falloff at the frame edges. Colours are saturated primary plastic — red, yellow, blue — against a clean neutral grey-blue ground. Visible moulding seams, stud tops, fingerprints and a little dust, so it reads as a photograph of real bricks rather than a 3D render.', 'Any person present is a small brick minifigure with a printed face, not a real human.', '3D render look, ray-traced perfection, CGI gloss, cartoon illustration, dark moody lighting', '["macro","toy","photographic","product"]', 'hand', '2026-08-14T13:49:07.085Z', '2026-08-14T13:49:07.085Z');
